# Generated by Django 4.2.1 on 2023-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_article_published_date_article_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
