# Generated by Django 4.2.1 on 2023-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
