# Generated by Django 4.2.1 on 2023-07-09 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Index', '0006_remove_article_category_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
