# Generated by Django 4.2.1 on 2023-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0009_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
