# Generated by Django 4.2.1 on 2023-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpreference',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
