# Generated by Django 4.2.1 on 2023-07-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0002_topicpreference_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpreference',
            name='topics',
        ),
        migrations.AddField(
            model_name='topicpreference',
            name='topics',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Recommendations.topic'),
        ),
    ]
