# Generated by Django 4.2.1 on 2023-07-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0003_remove_topicpreference_topics_topicpreference_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicpreference',
            old_name='topics',
            new_name='topic',
        ),
    ]
