# Generated by Django 4.2.1 on 2023-07-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0004_rename_topics_topicpreference_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpreference',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Recommendations.topic'),
        ),
    ]
