# Generated by Django 4.2.1 on 2023-07-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recommendations', '0005_alter_topicpreference_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpreference',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Recommendations.topic'),
        ),
        migrations.AlterField(
            model_name='topicpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topicpreference',
            unique_together={('user', 'topic')},
        ),
    ]
