# Generated by Django 4.2.1 on 2023-07-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0006_alter_topicpreference_topic_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicpreference',
            unique_together=set(),
        ),
    ]
