# Generated by Django 4.2.1 on 2023-07-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0007_alter_topicpreference_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpreference',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
